### PR TITLE
Tiny fix

### PR DESCRIPTION
**Pull request by banyan**

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
📝  `html_url` looks good.
https://developer.github.com/v3/pulls/

**Comment by yuya-takeyama** [comment]
LGTM 👍

**Comment by yuya-takeyama** [comment]
Failed to deploy!
https://travis-ci.org/quipper/quipper-hubot/builds/129625928

@banyan 
Is this due to my authentication token?

```
body: "{\"id\":\"forbidden\",\"error\":\"You do not have permission to view on quipper-hubot. You need to have the view permission on this app.\"}" (does the app 'quipper-hubot' exist and does your account have access to it?)
failed to deploy
```

**Comment by banyan** [comment]
@yuya-takeyama 

Sorry for late reply. (I wasn't aware 🙇 )
It seems so, I've switched to CircleCI: https://github.com/quipper/quipper-hubot/pull/19

**Pull request merged**
